---
- name: Software | Utilities | Install packages
  ansible.builtin.package:
    name:
      - at
      - "{{ aws_cli }}"
      - curl
      - "{{ cron_package }}"
      - "{{ dns_utils_package }}"
      - jq
      - "{{ lm_sensors_package }}"
      - lsof
      - ncdu
      - neofetch
      - net-tools
      - "{{ nfs_client_package }}"
      - nmap
      - openssl
      - "{{ rename_package }}"
      - rsync
      - tldr
      - traceroute
      - tree
      - unzip
      - wget

- name: Software | Utilities | Exclude packages Rocky
  ansible.builtin.package:
    name:
      - bat
      - sshfs
  when: ansible_distribution != "Rocky"

- name: Software | Utilities | Install Helm
  ansible.builtin.shell: |
    curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  args:
    creates: /usr/local/bin/helm
  when: ansible_distribution != "Rocky"

- name: Software | Utilities | Install Kubernetes
  ansible.builtin.shell: |
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
    rm -f kubectl
  args:
    creates: /usr/local/bin/kubectl
  when: ansible_distribution in ["Debian", "Ubuntu"]
