---
- name: Software | Development | Install packages
  ansible.builtin.package:
    name:
      - "{{ python_package }}"
      - "{{ python_pip_package }}"
      - "{{ python_boto3 }}"
      - "{{ python_botocore }}"
      - "{{ python_virtualenv_package }}"
      - "{{ ruby }}"
    state: latest

- name: Software | Development | Install packages Arch
  community.general.pacman:
    name:
      - base-devel
  when: ansible_distribution == "Archlinux"

- name: Software | Development | Install packages Debian/Ubuntu
  ansible.builtin.apt:
    name:
      - build-essential
      - python-is-python3
    state: latest
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: Software | Development | Install packages Fedora/Rocky
  ansible.builtin.dnf:
    name:
      - "@Development Tools"
    state: latest
  when: ansible_distribution in ["Fedora", "Rocky"]
