---
- name: K3s | HA Proxy Nodes | Install packages
  ansible.builtin.package:
    name:
      - haproxy
      - keepalived
    state: latest

- name: K3s | HA Proxy Nodes | Generate HAProxy Config
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: "0644"
  register: haproxy_config

- name: K3s | HA Proxy Nodes | Generate Keepalived Config on LB-1
  vars:
    keepalived_state: "{{ lb_1_keepalived_state }}"
    keepalived_priority: "{{ lb_1_keepalived_priority }}"
  ansible.builtin.template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: "0644"
  when:
    - ansible_default_ipv4.address == lb_1_node_ip

- name: K3s | HA Proxy Nodes | Generate Keepalived Config on LB-2
  vars:
    keepalived_state: "{{ lb_2_keepalived_state }}"
    keepalived_priority: "{{ lb_2_keepalived_priority }}"
  ansible.builtin.template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: "0644"
  when:
    - ansible_default_ipv4.address == lb_2_node_ip

- name: K3s | HA Proxy Nodes | Restart HAProxy and KeepAlived
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
  loop:
    - haproxy
    - keepalived
  when: haproxy_config is changed