---
- name: Pre-run | Run local scripts
  tags: always
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Pre-run | Copying SSH keys
      ansible.builtin.shell: curl https://raw.githubusercontent.com/jokerwrld999/Scripting/main/tools/ssh/copy-ssh-keys.sh | bash > ./copy-ssh.log
      changed_when: false

    - name: Pre-run | Installing Ansible roles and collections
      ansible.builtin.command: ansible-galaxy install -r requirements.yml
      changed_when: false

- name: Pre-run | Status | Set timer
  tags: always
  hosts: all
  become: true
  pre_tasks:
    - name: Status | Start time
      ansible.builtin.set_fact:
        start_time: "{{ ansible_date_time.iso8601[:19] }}"

# - name: K3s HA Cluster
#   hosts: all
#   become: true
#   vars_files:
#     - main.yml
#   tasks:
#     - debug: msg="Working on..... {{ ansible_all_ipv4_addresses }}"
#       tags: ipv4
#       when:
#         - inventory_hostname in groups["k3s_server_nodes"]
#         - ansible_default_ipv4.address == server_node_ip

#     - name: Pre-configuring servers
#       block:
#         - name: Include bootstrap role
#           ansible.builtin.include_role:
#             name: jokerwrld999.bootstrap
#           tags: lxc, test

#       rescue:
#         - name: Pre-Configuration | Rescue
#           ansible.builtin.set_fact:
#             task_failed: true

- name: K3s HA Cluster
  hosts: all
  become: true
  vars_files:
    - main.yml
  roles:
    - k3s_ha_cluster

- name: Post-run | Cleaning up servers
  tags: always
  hosts: all
  become: true
  tasks:
    - name: Post-cleanup | Packages (arch)
      ansible.builtin.shell: |
        yes | pacman -Scc
      changed_when: false
      when: ansible_distribution == "Archlinux"

    - name: Post-cleanup | Packages' cache (debian and ubuntu)
      ansible.builtin.apt:
        autoclean: yes
      changed_when: false
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: Post-cleanup | Autoremove orphan packages (debian and ubuntu)
      ansible.builtin.apt:
        autoremove: yes
        purge: yes
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: Post-cleanup | Package's cache (fedora/rocky)
      ansible.builtin.dnf:
        autoremove: yes
      when: ansible_distribution in ["Fedora", "Rocky"]

    - name: Status | Get runtime
      ansible.builtin.set_fact:
        runtime: "{{ ((ansible_date_time.iso8601[:19] | to_datetime('%Y-%m-%dT%H:%M:%S')) - (start_time | to_datetime('%Y-%m-%dT%H:%M:%S'))) }}"

# - name: Telegram Alerts | Send alerts
#   tags: always
#   hosts: all
#   vars_files:
#     - main.yml
#   tasks:
#     - name: Include bootstrap role
#       ansible.builtin.include_role:
#         name: jokerwrld999.telegram-alerts
