---
- name: Server Configuration
  block:
    - name: K3s HA Cluster | Server Nodes
      ansible.builtin.import_tasks: k3s_ha_cluster/k3s_server_nodes.yml
      when:
        - inventory_hostname in groups["k3s_server_nodes"]

    - name: K3s HA Cluster | Agent Nodes
      ansible.builtin.import_tasks: k3s_ha_cluster/k3s_agent_nodes.yml
      when:
        - inventory_hostname in groups["k3s_agent_nodes"]

  rescue:
    - name: Server Configuration | Rescue
      ansible.builtin.set_fact:
        task_failed: true
