---
- name: Users | Root | Install Git, ZSH
  ansible.builtin.package:
    name:
      - git
      - zsh

- name: Users | {{ custom_user }} | Create user's group
  ansible.builtin.group:
    name: "{{ custom_user }}"
    state: present

- name: Users | {{ custom_user }} | Create user
  ansible.builtin.user:
    name: "{{ custom_user }}"
    group: "{{ custom_user }}"
    groups: "{{ sudo_group }}"
    append: true
    password: "{{ custom_user_passwd }}"
    update_password: on_create
    shell: /bin/zsh
    state: present

- name: Users | {{ custom_user }} | Stat sudoers file
  ansible.builtin.stat:
    path: "/etc/sudoers.d/sudoers_{{ custom_user }}"
  register: sudoers_file

- name: Users | {{ custom_user }} | Copy sudoers file
  ansible.builtin.copy:
    src: "users/sudoers_custom_user"
    dest: "/etc/sudoers.d/sudoers_{{ custom_user }}"
    owner: root
    group: root
    mode: 0440
  register: new_sudoers_file
  when: sudoers_file.stat.exists == false

- name: Users | {{ custom_user }} | Change sudoers file
  ansible.builtin.lineinfile:
    dest: "/etc/sudoers.d/sudoers_{{ custom_user }}"
    regexp: "^custom_user"
    line: "{{ custom_user }} ALL=(ALL) NOPASSWD: ALL"
  when: new_sudoers_file.changed

- name: Users | Custom user | Reconnect to server session
  ansible.builtin.meta: reset_connection
