---
- name: Pre-Configuration | Include Distro Variables
  ansible.builtin.include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- name: Pre-Configuration
  block:
    # User Configuration
    - name: Pre-Configuration | Configure Custom User
      ansible.builtin.import_tasks: user_setup/user_config.yml
      tags:
        - development
        - docker

    # Install software
    - name: Pre-Configuration | Configure Repositories
      ansible.builtin.import_tasks: software/repositories.yml
      tags:
        - development
        - docker

    - name: Pre-Configuration | Configure Dev Packages
      ansible.builtin.import_tasks: software/packages_development.yml
      tags:
        - development
        - docker

    - name: Pre-Configuration | Configure Docker
      ansible.builtin.import_tasks: software/packages_docker.yml
      tags:
        - development
        - docker

    - name: Pre-Configuration | Configure Utilities
      ansible.builtin.import_tasks: software/packages_utilities.yml

    # Perform remaining tasks:
    - name: Pre-Configuration | Configure Logging
      ansible.builtin.import_tasks: system_setup/logging.yml

    - name: Pre-Configuration | Configure Microcode
      ansible.builtin.import_tasks: system_setup/microcode.yml
      tags:
        - microcode

    - name: Pre-Configuration | Configure OpenSSH
      ansible.builtin.import_tasks: system_setup/openssh.yml
      tags:
        - ssh

    - name: Pre-Configuration | Install Qemu Guest Agent
      ansible.builtin.import_tasks: system_setup/qemu-agent.yml

  rescue:
    - name: Pre-Configuration | Rescue
      ansible.builtin.set_fact:
        task_failed: true
