---
- name: Converge
  hosts: all
  # become: true
  # gather_facts: false

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == "Debian"

    # - name: Install test dependencies (RedHat).
    #   package: name=which state=present
    #   when: ansible_os_family == 'RedHat'

    # - name: Install test dependencies.
    #   package: name=curl state=present

  roles:
    - role: jokerwrld999.bootstrap
