Vagrant.configure("2") do |config|
	(1..3).each do |i|
		config.vm.define "k3s_controller#{i}" do |controller|
			controller.vm.box = "bento/ubuntu-18.04"
			controller.vm.network "forwarded_port", guest: 22, host: 2210 + i, id: "ssh"
			controller.vm.network "private_network", ip: "192.168.56.#{10 + i}", virtualbox__intnet: true
			controller.vm.hostname = "k3s_controller#{i}"

			controller.vm.provision "file", source: "~/.ssh/id_ed25519.pub", destination: "/home/vagrant/.ssh/key.pub"
			controller.vm.provision "shell", inline: <<-SHELL
				cat /home/vagrant/.ssh/key.pub >> /home/vagrant/.ssh/authorized_keys
				rm /home/vagrant/.ssh/key.pub
			SHELL

			controller.vm.provider "virtualbox" do |v|
				v.name = "k3s_contoller#{i}"
				v.memory = 2048
				v.cpus = 1
        v.customize ["modifyvm", :id, "--natnet1", "10.240.0.0/24"]
			end
		end
	end

  (1..3).each do |i|
		config.vm.define "k3s_agent#{i}" do |agent|
			agent.vm.box = "bento/ubuntu-18.04"
			agent.vm.network "forwarded_port", guest: 22, host: 2230 + i, id: "ssh"
			agent.vm.network "private_network", ip: "192.168.56.#{30 + i}", virtualbox__intnet: true
			agent.vm.hostname = "k3s_agent#{i}"

			agent.vm.provision "file", source: "~/.ssh/id_ed25519.pub", destination: "/home/vagrant/.ssh/key.pub"
			agent.vm.provision "shell", inline: <<-SHELL
				cat /home/vagrant/.ssh/key.pub >> /home/vagrant/.ssh/authorized_keys
				rm /home/vagrant/.ssh/key.pub
			SHELL

			agent.vm.provider "virtualbox" do |v|
				v.name = "k3s_agent#{i}"
				v.memory = 2048
				v.cpus = 1
        v.customize ["modifyvm", :id, "--natnet1", "10.240.0.0/24"]
			end
		end
	end
end