---
aws_cli: awscli
autojump_package: autojump-zsh
amd_microcode_package: microcode_ctl
cron_package: cronie
docker_compose: docker-compose-plugin
dns_utils_package: bind-utils
intel_microcode_package: microcode_ctl
lm_sensors_package: lm_sensors
nfs_client_package: nfs-utils
openssh_package: openssh-server
openssh_service: sshd
python_package: python3
python_pip_package: python3-pip
python_boto3: python3-boto3
python_botocore: python3-botocore
python_virtualenv_package: python3-virtualenv
rename_package: prename
ruby: ruby
sudo_group: wheel
qemu_agent_service: qemu-guest-agent
