apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  namespace: namespace-1
  labels:
    type: webserver
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
      - containerPort: 80