---
- name: Docker login
  community.docker.docker_login:
    registry_url: "{{ registry_url }}"
    username: "{{ docker_username }}"
    password: "{{ docker_pass }}"

- name: Deploying {{ container_name }} Container
  community.docker.docker_container:
    name: "{{ container_name }}"
    image: "{{ docker_image }}"
    published_ports: "{{ published_ports }}"
    state: started
