---
- name: System setup | Microcode | Check Processor Architecture
  ansible.builtin.command: lscpu | grep Intel
  register: check_processor
  changed_when: false
  failed_when: false

- name: System setup | Microcode | Install package Intel
  ansible.builtin.package:
    name: "{{ intel_microcode_package }}"
    state: latest
  when: check_processor.rc == 1

- name: System setup | Microcode | Install package AMD
  ansible.builtin.package:
    name: "{{ amd_microcode_package }}"
    state: latest
  when: check_processor.rc == 0
