---
- name: System setup | OpenSSH | Install package
  ansible.builtin.package:
    name: "{{ openssh_package }}"
    state: latest
  notify: Restart sshd

- name: System setup | OpenSSH | Ensure we have our version of sshd_config file
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^# Modified by"
    state: absent
  check_mode: yes
  changed_when: false
  register: sshd_template

- name: System setup | OpenSSH | Generate sshd_config file from template
  ansible.builtin.template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  when: not sshd_template.found

- name: System setup | OpenSSH | Check for WSL
  ansible.builtin.command: systemd-detect-virt
  register: virt_env_output
  changed_when: false

- name: System setup | OpenSSH | Update port for WSL
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "Port 22"
    line: "Port 2222"
  failed_when: false
  when: virt_env_output.stdout == "wsl"

- name: System setup | OpenSSH | Enable daemon
  ansible.builtin.service:
    name: "{{ openssh_service }}"
    enabled: yes
    state: started

- name: System setup | OpenSSH | Generate an OpenSSH keypair
  become: false
  community.crypto.openssh_keypair:
    type: ed25519
    path: ~/.ssh/ed25519
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
  connection: local

- name: System setup | OpenSSH | Stat SSH Identity Config
  become: false
  ansible.builtin.stat:
    path: "~/.ssh/config"
  connection: local
  register: ssh_identity

- name: System setup | OpenSSH | New SSH Identity config
  become: false
  ansible.builtin.copy:
    dest: "~/.ssh/config"
    content: |
      IdentityFile ~/.ssh/ed25519
  connection: local
  register: new_ssh_identity
  when: ssh_identity.stat.exists == false

- name: System setup | OpenSSH | Set Default Identity
  become: false
  ansible.builtin.lineinfile:
    dest: "~/.ssh/config"
    line: "IdentityFile ~/.ssh/ed25519"
    state: present
  connection: local
  when: not new_ssh_identity.changed

- name: System setup | OpenSSH | Copy SSh Key
  become_user: "{{ custom_user }}"
  ansible.posix.authorized_key:
    user: "{{ custom_user }}"
    state: present
    key: "{{ lookup('file', '~/.ssh/ed25519.pub') }}"
