---
- name: System setup | Qemu-agent | Check for KVM
  ansible.builtin.command: systemd-detect-virt
  register: virt_env_output
  changed_when: false

- name: System setup | Qemu-agent | Install package
  ansible.builtin.package:
    state: latest
    name:
      - qemu-guest-agent
  when: virt_env_output.stdout == "kvm"
  register: qemu_install

- name: System setup | Qemu-agent | Enable qemu agent daemon
  ansible.builtin.service:
    name: "{{ qemu_agent_service }}"
    enabled: yes
  when: qemu_install.changed

- name: System setup | Qemu-agent | Reboot the machine
  ansible.builtin.reboot:
  when: qemu_install.changed
